#!/usr/bin/env bash

cp -av myfiles/datasets/00267_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00217_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00162_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00000_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00112_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00239_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00070_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00225_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00091_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00183_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00255_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00120_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00042_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00150_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00032_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00135_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00057_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00145_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00027_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00079_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00230_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00084_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00009_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00196_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00240_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00177_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00015_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00107_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00098_twitter.JPG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00065_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00272_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00159_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00202_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00129_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00193_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00245_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00081_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00235_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00022_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00140_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00052_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00130_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00207_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00277_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00229_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00060_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00102_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00259_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00010_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00172_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00075_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00088_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00117_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00005_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00167_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00139_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00212_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00149_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00262_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00037_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00155_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00283_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00047_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00125_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00186_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00019_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00250_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00094_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00069_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00220_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00253_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00185_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00178_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00223_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00097_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00108_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00280_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00156_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00034_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00126_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00044_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00211_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00058_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00261_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00028_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00114_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00076_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00164_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00199_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00006_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00101_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00063_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00171_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00013_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00204_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00274_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00143_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00021_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00268_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00133_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00051_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00218_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00246_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00190_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00236_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00082_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00271_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00038_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00201_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00048_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00016_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00189_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00174_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00066_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00104_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00118_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00087_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00233_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00168_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00243_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00195_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00054_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00136_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00024_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00146_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00041_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00208_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00123_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00031_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00278_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00285_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00153_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00092_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00226_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00256_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00180_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00003_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00161_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00073_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00111_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00264_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00214_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00124_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00046_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00282_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00154_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00036_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00221_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00068_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00095_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00251_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00018_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00187_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00166_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00004_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00116_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00089_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00074_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00263_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00148_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00213_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00138_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00276_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00206_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00173_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00011_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00258_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00103_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00061_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00228_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00234_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00080_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00244_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00192_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00131_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00053_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00141_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00023_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00064_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00099_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00106_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00014_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00176_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00128_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00203_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00158_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00273_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00026_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00144_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00056_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00134_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00241_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00197_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00008_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00085_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00231_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00078_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00254_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00182_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00090_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00224_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00033_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00151_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00043_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00121_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00216_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00266_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00071_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00238_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00113_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00001_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00248_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00163_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00110_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00072_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00160_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00002_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00215_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00265_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00152_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00284_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00279_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00030_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00122_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00209_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00040_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00181_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00257_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00227_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00093_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00194_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00242_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00169_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00232_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00086_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00119_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00147_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00025_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00137_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00055_twitter.JPG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00049_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00200_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00039_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00270_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00105_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00067_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00175_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00188_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00017_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00219_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00050_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00132_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00269_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00020_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00142_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00083_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00237_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00191_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00247_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00012_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00170_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00062_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00100_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00275_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00205_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00029_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00260_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00059_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00210_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00007_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00198_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00165_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00077_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00115_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00109_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00096_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00222_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00179_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00184_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00252_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00045_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00127_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00035_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00157_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
cp -av myfiles/datasets/00281_twitter.PNG ~/Downloads/datasets/twitter_screenshots_localization_dataset/train_images/
