name: pytorch-lab3
channels:
  - pytorch
  - conda-forge
  - defaults
  - fastchan
  - apple
dependencies:
  - python=3.10
  - pip>=22.2
  - pytorch
  # - pytorch-lightning=1.7
  - torchmetrics
  - torch-fidelity
  - torchtext
  - torchvision
  - fastai=2.7.10
  - albumentations=1.3.0
  - timm

  # I suggest to keep the other deps sorted for convenience.
  # To determine what the latest versions should be, run:
  #
  # ```shell
  # sed -E 's/invokeai/invokeai-updated/;20,99s/- ([^=]+)==.+/- \1/' environment-mac.yml > environment-mac-updated.yml
  # CONDA_SUBDIR=osx-arm64 conda env create -f environment-mac-updated.yml && conda list -n invokeai-updated | awk ' {print "  - " $1 "==" $2;} '
  # ```

  - coloredlogs=15.0
  - eventlet
  - humanfriendly=10.0
  - imageio=2.21
  - imageio-ffmpeg=0.4
  - imgaug=0.4
  - numpy=1.23
  - openh264=2.3
  # - pudb=2019.2
  - py-opencv=4.6
  - scipy=1.9
  - tensorboard=2.11.0
  - transformers=4.23
  - matplotlib=3.6.2
  - scikit-image
  - scikit-learn
  - apple::tensorflow-deps
  - pip:
      - tqdm
      - better_exceptions
      - torchsummary
      - bpython
      - imutils
      - uritools
      - rich[jupyter]
      - icecream
      - black[jupyter]
      - pylint
      - isort
      - autopep8
      - autoflake
      - pdbpp
      - mlxtend
      - torchinfo
      - invoke
      - logging_tree
      - loguru
      - pydantic[email]
      - picklescan
      - git+https://github.com/openai/CLIP.git@main#egg=clip
      - git+https://github.com/Birch-san/k-diffusion.git@mps#egg=k-diffusion
      - viztracer
      # - pdbr
      - pytype
      - pyannotate
      # - prospector
      # - vulture
      - mypy
      # - bandit
      - py-spy
      - watermark
      - pyfiglet
      - pynguin
      - memray
      - torch-tb-profiler
      # - label-studio
      # - tensorflow-addons
      # - tensorflow-data-validation
      # https://developer.apple.com/metal/tensorflow-plugin/
      # - tensorflow-datasets
      # - tensorflow-estimator
      # - tensorflow-hub
      # - tensorflow-metadata
      # - tensorflow-model-analysis
      # - tensorflow-probability
      # - tensorflow-serving-api
      # - tensorflow-transform
      - tensorflow-macos
      - tensorflow-metal
      - webcolors
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
